### ISSUE TITLE
po update throws error

### ISSUE THREAD

**Issue by kasperkamperman** [nrobinson2000/po#2]
Hi just was updating to the latest version and I get the error below:
nrobinson2000/newpo/newpo 0.2.8 -> 0.3.5

I tried running po update again (after po install) to see if this happens in 0.3.5 and indeed the same error was thrown. 

```
Updating particle-cli...
Password:
module.js:549
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

**Comment by nrobinson2000** [comment]
You should first switch to the latest version of po. I recently changed it back to `nrobinson2000/po`. To do this you can do:

```
brew uninstall --force gcc-arm-none-eabi-53
brew uninstall --force po
brew untap nrobinson2000/newpo

brew tap nrobinson2000/po
po install
```

To fix the npm error try this:

```
sudo npm uninstall -g --unsafe-perm particle-cli
sudo npm install -g --unsafe-perm particle-cli
```

**Comment by kasperkamperman** [comment]
I've tried this the particle-cli error seems to persist (I get this error with all 3 commands at the end).

**Comment by nrobinson2000** [comment]
This is definitely a particle-cli exclusive issue.

[You might have luck using this method, which I'll integrate into po soon.](https://docs.particle.io/guide/tools-and-features/cli/photon/#using-macos-or-linux)

**Comment by nrobinson2000** [comment]
If you're still in the Particle space I'd recommend upgrading to [neopo](https://nrobinson2000.github.io/neopo/), a replacement for po-util written in Python.

Here is the repository:
https://github.com/nrobinson2000/neopo
